name: flutter_application_shuttle_bus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  permission_handler: ^10.4.5
  flutter_naver_map: ^1.3.1
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/ # 인증 설정 파일을 포함하도록 assets 등록
